openapi: 3.0.0
info:
  title: Financial Market API
  description: API to retrieve stock market quotes
  version: 1.0.0
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com

tags:
  - name: Stock Quotes
    description: Operations related to stock quotes

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging.api.example.com/v1
    description: Staging server

paths:
  /quotes:
    get:
      summary: Returns stock quotes
      description: Retrieves the current price of a specific stock
      operationId: getStockQuotes
      tags:
        - Stock Quotes
      parameters:
        - name: symbol
          in: query
          required: true
          description: Stock symbol (e.g., AAPL, TSLA)
          schema:
            type: string
            minLength: 3
            maxLength: 5
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol:
                    type: string
                    description: Stock symbol
                    example: "AAPL"
                    maxLength: 5  # ✅ Adicionado maxLength correto
                  price:
                    type: number  # ✅ Corrigido: agora é um número (sem maxLength)
                    description: Current stock price
                    example: 150.75
                  currency:
                    type: string
                    description: Quote currency
                    example: "USD"
                    maxLength: 3  # ✅ Adicionado maxLength correto
        "400":
          description: Invalid request (missing or incorrect stock symbol)
