name: 🔍 Validação da Spec com Spectral e Linting YAML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-spec:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout do código
        uses: actions/checkout@v3

      - name: 📄 Verificar formatação do YAML (YAML Lint)
        uses: actionshub/yamllint@v1
        with:
          file_or_dir: "spec/"  # Analisa todos os arquivos dentro da pasta spec

      - name: ⚡ Configurar Node.js
        uses: actions/setup-node@v18
        with:
          node-version: "18"

      - name: 📦 Instalar Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: 🔍 Validar Spec OpenAPI com Spectral
        run: spectral lint spec/api-financeira.yaml --ruleset spec/spectral-rules.yaml
